# Generated by Django 5.0.6 on 2024-05-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='teamid',
            new_name='teamname',
        ),
        migrations.RenameField(
            model_name='playerfeedback',
            old_name='Playerid',
            new_name='Playername',
        ),
    ]
